---

- name: "Copy artifact into Instance" 
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz


- name: "Start app"
  become: true
  shell: |
    cd /home/ubuntu
    tar xzvf artifact.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start